version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault-test
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
    cap_add:
      - IPC_LOCK

  vault-prod:
    image: hashicorp/vault:1.15
    container_name: vault-prod
    ports:
      - "8202:8200"
    volumes:
      - ./vault-data:/vault/data
      - ./test-config/vault.hcl:/vault/config/vault.hcl:ro
    cap_add:
      - IPC_LOCK
    command: ["vault", "server", "-config=/vault/config/vault.hcl"]